service:
  name: products-service
frameworkVersion: '2'

useDotenv: true

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ${env:AWS_REGION}
  httpApi:
    cors: true
  environment:
    PG_HOST: ${env:PG_HOST}
    PG_PORT: ${env:PG_PORT}
    PG_DATABASE: ${env:PG_DATABASE}
    PG_USERNAME: ${env:PG_USERNAME}
    PG_PASSWORD: ${env:PG_PASSWORD}
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
    excludeFiles: src/**/*.test.js
  dotenv:
    required:
      file: true
functions:
  products:
    handler: products.handler
    events:
      - httpApi:
          method: get
          path: /products
  productById:
    handler: productById.handler
    events:
      - httpApi:
          method: get
          path: /products/{id}
  productCreate:
    handler: productCreate.handler
    events:
      - httpApi:
          method: post
          path: /products
