service:
  name: import-service
frameworkVersion: "2"

useDotenv: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ${env:REGION}
  environment:
    SQS_URL:
      Ref: SQSQueue
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::${env:BUCKET}"
    - Effect: "Allow"
      Action: 
        - "s3:*"
      Resource:
        - "arn:aws:s3:::${env:BUCKET}/*"
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource:
        - Fn::GetAtt:
          - SQSQueue
          - Arn
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
    excludeFiles: tests/**/*.test.js
functions:
  importProductsFile:
    handler: handlers/importProductsFile.handler
    events:
      - httpApi:
          method: get
          path: /import
          cors: true
  importFileParser:
    handler: handlers/importFileParser.handler
    events:
      - s3:
          bucket: ${env:BUCKET}
          event: s3:ObjectCreated:*
          rules: 
            - prefix: uploaded/
          existing: true
resources:
  Resources:
    SQSQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
  Outputs:
    SqsQueueArn:
      Value: !GetAtt SQSQueue.Arn
      Export:
        Name: SQSQueueArn
