service:
  name: authorization-service
frameworkVersion: '2'

useDotenv: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ${env:REGION}
custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    includeModules: true
    packager: 'npm'
  dotenv:
    required:
      file: true
functions:
  basicAuthorizer:
    handler: handlers/basicAuthorizer.handler
resources:
  Outputs:
    BasicAuthorizerArn:
      {
        Value: { 'Fn::GetAtt': ['BasicAuthorizerLambdaFunction', 'Arn'] },
        Export: { Name: 'BasicAuthorizerArn' }
      }
